Additional task for first Lab for CSharp course
Wlix13/msu-fiit pull request #10
Opened 2024-10-04 17:24 UTC by Wlix13

2024-10-05 14:26 UTC, Arasfon requested changes

2024-10-05 14:26 UTC, Arasfon commented on 3course/CSharp/lab1/Program.cs
> +public delegate void Fy3Values (double x, ref Complex y3);
Redundant space between delegate parameters and delegate name

2024-10-07 09:45 UTC, Wlix13 commented on 3course/CSharp/lab1/Program.cs
> +public delegate void Fy3Values (double x, ref Complex y3);
I was thinking of separating main task and an additional task, maybe I should just add a comment to this delegate. Only one file is used for the whole lab

2024-10-07 10:42 UTC, Arasfon approved these changes
LGTM

2024-10-07 10:45 UTC, merged